# filepath: WebSocketBridge.yml
name: 1.2.$(Rev:r)
trigger:
 branches:
   include:
     - main
jobs:
  - job: Build
    displayName: Build Solution
    pool:
      name: Default
    steps:
      - checkout: self
        fetchDepth: 1
        clean: true
    
      - task: DotNetCoreCLI@2
        displayName: Build Projects
        inputs:
          command: 'build'
          arguments: '--configuration Release -p:Version="$(Build.BuildNumber)"'
          projects: '**/*.csproj'
      
      - task: PublishPipelineArtifact@1
        displayName: Publish Build Artifacts
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)
          artifact: BuildOutput
          publishLocation: pipeline

  - job: Publish_NuGet
    displayName: Publish NuGet Package
    dependsOn: Build
    pool:
      name: Default
    workspace:
      clean: true
    steps:
      - download: current
        artifact: BuildOutput

      - task: NuGetCommand@2
        displayName: Push NuGet Package
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/BuildOutput/Bitbound.WebSocketBridge.Common/bin/Release/**/*.nupkg;!$(Pipeline.Workspace)/BuildOutput/Bitbound.WebSocketBridge.Common/bin/Release/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'NuGet'

  - job: Publish_Docker
    displayName: Build and Push Docker Image
    dependsOn: Build
    pool:
      name: Default
    workspace:
      clean: true
    steps:
      - download: current
        artifact: BuildOutput
        
      - task: Docker@2
        displayName: Build and Push Docker
        inputs:
          containerRegistry: 843c64d8-bb79-4b00-8a18-f721cb8c9318
          repository: translucency/websocket-bridge
          buildContext: $(Pipeline.Workspace)/BuildOutput
          tags: |
            $(Build.BuildId)
            latest
