name: $(date:yyyyMMdd)$(rev:.r)
trigger:
 branches:
   include:
     - main
jobs:
  - job: Docker_Deploy
    displayName: Docker Build and Deploy
    pool:
      name: Default
    steps:
      - checkout: self
        fetchDepth: 1

      - task: Docker@2
        displayName: Build and Push Docker
        inputs:
          containerRegistry: 428e5669-4949-4ad6-9e37-730f15b2cad8
          repository: translucency/websocket-bridge
          buildContext: $(System.DefaultWorkingDirectory)
          tags: >-
            $(Build.BuildId)

            latest
