name: 1.2.$(Rev:r)
trigger:
 branches:
   include:
     - main
jobs:
  - job: Docker_Deploy
    displayName: Docker Build and Deploy
    pool:
      name: Default
    steps:
      - checkout: self
        fetchDepth: 1
        clean: true
    
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration Release -p:Version="$(Build.BuildNumber)"'
          projects: '**/*.csproj'
      
      - task: NuGetCommand@2
        inputs:
          command: 'push'
          packagesToPush: './Bitbound.WebSocketBridge.Common/bin/Release/**/*.nupkg;!./Bitbound.WebSocketBridge.Common/bin/Release/**/*.symbols.nupkg'
          nuGetFeedType: 'external'
          publishFeedCredentials: 'NuGet'

      - task: Docker@2
        displayName: Build and Push Docker
        inputs:
          containerRegistry: 843c64d8-bb79-4b00-8a18-f721cb8c9318
          repository: translucency/websocket-bridge
          buildContext: $(System.DefaultWorkingDirectory)
          tags: >-
            $(Build.BuildId)

            latest
