name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to use"
        required: true
        type: choice
        options:
          - preview
          - latest
        default: "preview"
  push:
    branches:
      - main

env:
  MAJOR_VERSION: 1
  MINOR_VERSION: 0

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Show Inputs
        run: |
          echo "Inputs: ${{ toJSON(github.event.inputs) }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          clean: true

      - name: Set version
        id: set_version
        run: |
          $version = "${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }}"
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "Version: $version"

      - name: Build project
        run: |
          dotnet build --configuration Release -p:Version="${{ steps.set_version.outputs.version }}" Bitbound.WebSocketBridge/Bitbound.WebSocketBridge.csproj

      # Add NuGet publishing step
      - name: Publish NuGet package
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet nuget push ./Bitbound.WebSocketBridge.Common/bin/Release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Bitbound.WebSocketBridge/Dockerfile
          push: true
          tags: |
            translucency/websocket-bridge:${{ steps.set_version.outputs.version }}
            translucency/websocket-bridge:${{ github.event.inputs.docker_tag }}
